import { ProductCatalogItem } from '../../../services/cart/cart.service';
export interface StoreProduct extends ProductCatalogItem { category: string; ingredients?: string; }
export const PRODUCTS: StoreProduct[] = [
  { id: 1, titulo: 'Torta Boutique de Pistacho y Rosas', descripcion: 'Bizcocho esponjoso de pistachos, crema mousseline de rosas y frutos rojos frescos.', descuento: '', precioActual: 185, precioAnterior: 0, etiqueta: 'Tortas', color: '', imagen: 'assets/figma/detail-main.png', category: 'Tortas', ingredients: 'Pistacho natural, harina de trigo, huevos de corral, azúcar de caña, agua de rosas orgánica, frambuesa y frutos de estación.' },
  { id: 2, titulo: 'Torta de Rosas & Champagne', descripcion: 'Bizcocho embebido en almíbar de champagne rosado, relleno de crema de fresa.', descuento: '', precioActual: 160, precioAnterior: 0, etiqueta: 'Tortas', color: '', imagen: 'assets/figma/catalog-roses.png', category: 'Tortas' },
  { id: 3, titulo: 'Selva Negra Contemporánea', descripcion: 'La receta tradicional alemana reinventada con mousse de chocolate belga y cerezas.', descuento: '', precioActual: 145, precioAnterior: 0, etiqueta: 'Tortas', color: '', imagen: 'assets/figma/catalog-selva.png', category: 'Tortas' },
  { id: 4, titulo: 'Cupcakes Dulce Brisa', descripcion: 'Delicados cupcakes de vainilla de Tahití con frosting celestial y perlas.', descuento: '', precioActual: 48, precioAnterior: 0, etiqueta: 'Cupcakes', color: '', imagen: 'assets/figma/catalog-cupcakes.png', category: 'Cupcakes' },
  { id: 5, titulo: 'Domo de Frambuesa & Pistacho', descripcion: 'Mousse de frambuesa aterciopelado con centro cremoso de pistacho.', descuento: '', precioActual: 22, precioAnterior: 0, etiqueta: 'Postres Individuales', color: '', imagen: 'assets/figma/catalog-raspberry.png', category: 'Postres Individuales' },
  { id: 6, titulo: 'Alfajores de Maicena Especiales', descripcion: 'Caja de 12 unidades súper suaves con generoso manjar blanco artesanal.', descuento: '', precioActual: 35, precioAnterior: 0, etiqueta: 'Bocaditos', color: '', imagen: 'assets/figma/catalog-alfajores.png', category: 'Bocaditos' },
  { id: 7, titulo: 'Tarta Limón y Lavanda Infundida', descripcion: 'Crema de limón cítrica, merengue suizo e infusión sutil de flores.', descuento: '', precioActual: 85, precioAnterior: 0, etiqueta: 'Ocasiones Especiales', color: '', imagen: 'assets/figma/catalog-lemon.png', category: 'Ocasiones Especiales' },
];
