
export class Cotizacion {
  icod_cotizacion: number;
  anio_cotizacion: number;
  numero_cotizacion: string;
  fecha_cotizacion: string;  
  icod_cliente: number;
  vcod_cliente: string;
  nombre_cliente: string;
  direccion_cliente: string;
  dni_cliente: string;
  ruc_cliente: string;
  correo_cliente: string;
  direccion_cliente_cliente: string;
  cruz_cliente: string;
  telefono_cliente: string;
  porcentaje_igv: number;
  monto_sub_total: number;
  monto_impuesto: number;
  monto_total: number;
  situacion_oc: number;
  descripcion_situacion: string;
  forma_pago: number;
  incluido_igv: boolean;
  atencion: string;
  forma_pago_detalle: string;
  tiempo_entrega: string;
  lugar_entrega: string;
  nota_cotizacion: string;
  referencia_cotizacion: string;
  envio_provincia: string;
  tipo_pago: number;
  monto_pagado: number;
  monto_saldo: number;
  monto_vuelto: number;
  nombre_vendedor: string;
  porcentaje_descuento: number;
  monto_descuento: number;
  tipo_documento_id: number;
  tipo_documento_abreviatura: string;
  tipo_documento_descripcion: string;
  nota_venta_id: number;
  numero_nota_venta: string;
  estado_guia: string;
  remision_id: number;
  vendedor_Id: number;
  fecha_creacion_cotizacion: string;  
  fecha_creacion: string;   
  usuario_creacion: string;
  usuario_modificacion: number;
  fecha_modificacion: string;   
  usuario_modificacion_detalle: string;

  constructor() {
    this.icod_cotizacion = 0;
    this.anio_cotizacion = 0;
    this.numero_cotizacion = '';
    this.fecha_cotizacion = '';
    this.icod_cliente = 0;
    this.vcod_cliente = '';
    this.nombre_cliente = '';
    this.direccion_cliente = '';
    this.dni_cliente = '';
    this.ruc_cliente = '';
    this.correo_cliente = '';
    this.direccion_cliente_cliente = '';
    this.cruz_cliente = '';
    this.telefono_cliente = '';
    this.porcentaje_igv = 0;
    this.monto_sub_total = 0;
    this.monto_impuesto = 0;
    this.monto_total = 0;
    this.situacion_oc = 0;
    this.descripcion_situacion = '';
    this.forma_pago = 0;
    this.incluido_igv = true;
    this.atencion = '';
    this.forma_pago_detalle = '';
    this.tiempo_entrega = '';
    this.lugar_entrega = '';
    this.nota_cotizacion = '';
    this.referencia_cotizacion = '';
    this.envio_provincia = '';
    this.tipo_pago = 0;
    this.monto_pagado = 0;
    this.monto_saldo = 0;
    this.monto_vuelto = 0;
    this.nombre_vendedor = '';
    this.porcentaje_descuento = 0;
    this.monto_descuento = 0;
    this.tipo_documento_id = 0;
    this.tipo_documento_abreviatura = '';
    this.tipo_documento_descripcion = '';
    this.nota_venta_id = 0;
    this.numero_nota_venta = '';
    this.estado_guia = '';
    this.remision_id = 0;
    this.vendedor_Id = 0;
    this.fecha_creacion_cotizacion = '';
    this.fecha_creacion = '';
    this.usuario_creacion = '';
    this.usuario_modificacion = 0;
    this.fecha_modificacion = '';
    this.usuario_modificacion_detalle = '';
  }
}
