import { CotizacionVentaDetalle } from "./cotizacionDetalle";

export interface CotizacionVenta {
  ctvcIcodCotizacionVenta: number;
  ctvcIanio: number;
  ctvcNumeroCotizacionVenta: string;
  ctvcSfechaCotizacionVenta: string;  
  cliecIcodCliente: number;
  cliecVcodCliente: string;
  tablcIidTipoMoneda: number;
  ctvcNporImpIgv: number;
  ctvcNmontoSubTotal: number;
  ctvcNmontoImp: number;
  ctvcNmontoTotal: number;
  tablcIidSituacionOc: number;
  tablcIformaPago: number;
  ctvcBIncluidoIgv: boolean;
  ctvcIusuarioCrea: number;
  ctvcVpcCrea: string;
  ctvcFlagEstado: boolean;
  ctvcVatencion: string;
  ctvcVformaPago: string;
  ctvcVtiempoEntrega: string;
  ctvcVvalidezOferta: string;
  ctvcVlugarEntrega: string;
  ctvcVnotaCotizacion: string;
  ctvcVreferencia: string;
  ctvcNumeroTelefono: string;
  cliecVnombreCliente: string;
  cliecVDniCliente: string;
  cliecVRuc: string;
  cliecVCorreo: string;
  cliecVNumero: string;
  ctvIdLugarEntrega: number;
  idLogo: number;
  logVNombre: string;
  ctcvEnvio: boolean;
  tablcItipoPago: number;
  ctvcMontoPago: number;
  ctvcMontoSaldo: number;
  vdrscIcodVendedor: number;
  ctvdPocDescuento: number;
  ctvdMontoDescuento: number;
  tdoccIcodTipoDoc: number;
  ctvdMontoVuelto: number;
  detalles: CotizacionVentaDetalle[];
}
